version: '3'

services:
  prometheus:
    ports:
      - 9090:9090

  blackbox-exporter:
    ports:
      - 9115:9115

  node-exporter:
    ports:
      - 9100:9100

  grafana:
    ports:
      - 3000:3000

  alertmanager:
    ports:
      - 9093:9093
