version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./etc/nginx/auth:/etc/nginx/auth
      - ./public:/var/www/public:ro
    depends_on:
      - grafana
    networks:
      - internal
