groups:
- name: Blackbox alerts
  rules:

  - alert: certificate_invalid
    expr: probe_http_ssl == 0
    for: 1d
    labels:
      severity: critical
    annotations:
      summary: "SSL-сертификат недействителен или отсутствует"

  - alert: certificate_validity_10_days
    expr: (probe_ssl_earliest_cert_expiry - time ()) < ( 60 * 60 * 24 * 10 )
    for: 1d
    labels:
      severity: warning
    annotations:
      summary: "Срок действия SSL-сертификата истекает менее чем через 10 дней"

  - alert: invalid_http_response_code
    expr: probe_http_status_code < 200 OR probe_http_status_code >= 400
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Неверный код статуса ответа"

  - alert: http_slow_request
    expr: avg_over_time(probe_http_duration_seconds[1m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "HTTP-запрос занял более 5 секунд"
